### ISSUE TITLE
Cannot compile using rust < 1.63

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#730]
**Describe the bug**
Using a toolchain lower than 1.63 results in compilation error

**Additional context**
Arbitrary has released a new patch version `1.1.4` that use a new core function introduced in rust `1.63` https://github.com/rust-fuzz/arbitrary/commit/cf0516e4c3c16e04713b252b6327fb7607823a22
